export enum PAYMENT_STATUSES {
  PENDING = "PENDING",
  SUCCESS = "SUCCESS",
  FAILED = "FAILED",
}

export enum PAYMENT_METHODS {
  BANK_TRANSFER = "BANK_TRANSFER",
  CARD = "CARD",
  MANUAL = "MANUAL",
}
